name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * MON"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 17
        check-latest: true
    - run: pnpm install
    - run: pnpm run build
    - name: Git Identity
      run: |
        git config --global user.name 'vinzius'
        git config --global user.email 'vincent.germain@mac.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: pnpm lerna publish -y --create-release github --no-verify-access
      env:
        HUSKY: 0
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
